# .github/workflows/playwright.yml
name: Playwright Tests

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps

      - name: Prepare config.toml without comments
        run: |
          grep -v '^\s*#' config.toml.sample | grep -v '^\s*$' > config.toml

      - name: Run Relay
        run: pnpm run relay

      - name: Build project
        run: pnpm run build

      - name: Serve build at port 9081
        run: npx serve -s dist -l 9081

      - name: Run Playwright Tests
        run: pnpm exec playwright test

      - name: Upload HTML report (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
