# .github/workflows/playwright.yml
name: Playwright Tests

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        lts:
          - name: "v25.6"
            apiEndpoint: "http://10.122.12.148/8090"
          - name: "v24.09"
            apiEndpoint: "http://10.122.10.126:8090"

    name: E2E Playwright Tests for LTS ${{ matrix.lts.name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps

      - name: Copy config.toml
        run: |
          awk -v ep="${{ matrix.lts.apiEndpoint }}" '
            /^[[:space:]]*$/ { next }
            /^\[.*\]$/ { if (n++) print ""; print; next }
            /^[[:space:]]*#[^=]/ { print; next }
            {
              sub(/#.*/, "", $0)
              sub(/[[:space:]]+$/, "", $0)
              if ($0 ~ /^apiEndpoint[[:space:]]*=/)
                print "apiEndpoint = \"" ep "\""
              else if ($0 != "")
                print
            }
          ' config.toml.sample > config.toml

      - name: Prepare config.toml
        run: |
          sed -i 's|^apiEndpoint =.*|apiEndpoint = "http://127.0.0.1:9081"|' config.toml

      - name: Upload config.toml artifact
        uses: actions/upload-artifact@v4
        with:
          name: config-toml-${{ matrix.lts.name }}
          path: config.toml

      - name: Run Relay
        run: pnpm run relay

      - name: Build project
        run: pnpm run build

      - name: Serve build at port 9081 (background)
        run: |
          npx serve -s -l 9081 > /dev/null 2>&1 &
          echo "Waiting for server to start..."
          for i in {1..30}; do
            if curl -s http://127.0.0.1:9081 > /dev/null; then
              echo "Server is up!"
              break
            fi
            sleep 1
          done

      - name: Prepare .env.playwright with local server URL
        run: |
          cp e2e/envs/.env.playwright.sample e2e/envs/.env.playwright
          if grep -q '^BASE_URL=' e2e/envs/.env.playwright; then
            sed -i 's|^BASE_URL=.*|BASE_URL=http://127.0.0.1:9081|' e2e/envs/.env.playwright
          else
            echo 'BASE_URL=http://127.0.0.1:9081' >> e2e/envs/.env.playwright
          fi

      - name: Run Playwright Tests
        run: pnpm exec playwright test

      - name: Upload HTML report (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-${{ matrix.lts.name }}
          path: playwright-report/
