# .github/workflows/playwright.yml
name: Playwright Tests

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps

      - name: Prepare config.toml without comments
        run: |
          grep -v '^\s*#' config.toml.sample | grep -v '^\s*$' > config.toml

      - name: Run Relay
        run: pnpm run relay

      - name: Build project
        run: pnpm run build

      - name: Serve build at port 9081 (background)
        run: |
          npx serve -s dist -l 9081 > /dev/null 2>&1 &
          echo "Waiting for server to start..."
          for i in {1..30}; do
            if curl -s http://127.0.0.1:9081 > /dev/null; then
              echo "Server is up!"
              break
            fi
            sleep 1
          done

      - name: Prepare .env.playwright with local server URL
        run: |
          cp e2e/envs/.env.playwright.sample e2e/envs/.env.playwright
          if grep -q '^BASE_URL=' e2e/envs/.env.playwright; then
            sed -i 's|^BASE_URL=.*|BASE_URL=http://127.0.0.1:9081|' e2e/envs/.env.playwright
          else
            echo 'BASE_URL=http://127.0.0.1:9081' >> e2e/envs/.env.playwright
          fi

      - name: Run Playwright Tests
        run: pnpm exec playwright test

      - name: Upload HTML report (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
